### ISSUE TITLE
Crash on closing PSMS with USB connected navi controller

### ISSUE THREAD

**Issue by TenchiMasaki** [HipsterSloth/PSMoveSteamVRBridge#18]
[2017-06-20 07:18:14.649]: main - Starting PSMoveService v0.9-alpha 8.6.0
[2017-06-20 07:18:14.657]: USBAsyncRequestManager::startup - Requested LibUSBApi
[2017-06-20 07:18:14.658]: USBAsyncRequestManager::startup - Creating LibUSBApi
[2017-06-20 07:18:14.660]: USBAsyncRequestManager::startup - Initialized USB API
[2017-06-20 07:18:14.663]: DeviceManager::startup - Platform Hotplug API is ENABLED
[2017-06-20 07:18:14.691]: bluetooth_get_host_address - Found a bluetooth radio
[2017-06-20 07:18:14.692]: bluetooth_get_host_address - Retrieved radio info
[2017-06-20 07:18:14.823]: PSMoveController::open - Opening PSMoveController(\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#9&10b5aef1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
[2017-06-20 07:18:14.825]: PSMoveController::open -   with serial_number: 04766e082467
[2017-06-20 07:18:15.11]: DeviceTypeManager::update_connected_devices - Device device_id 0 (PSMove) opened
[2017-06-20 07:18:15.13]: PSNaviController::open - Opening PSNaviController(USB\VID_054C&PID_042F\b4_p1.2)
[2017-06-20 07:18:15.42]: USBAsyncRequestManager::openUSBDevice - Successfully opened device -1
[2017-06-20 07:18:15.43]: PSNaviController::open -   Successfully opened USB handle 0

**Comment by HipsterSloth** [comment]
Sorry this took me so long to reply back about this. It looks like you are connecting a PSNavi controller using USB (rather than bluetooth)? It looks like there were a few bugs in the USB device management code. That system had a big re-write a while ago and then didn't get a lot of testing. I have a custom build for you to try. Let me know if this works for you:

[PSMoveSteamVRBridge_1.3.1_custom1.zip](https://github.com/HipsterSloth/PSMoveSteamVRBridge/files/1100814/PSMoveSteamVRBridge_1.3.1_custom1.zip)

Also I assume you followed the USB setup instructions here:
https://github.com/cboulay/PSMoveService/wiki/PSNavi-Setup#connecting-over-usb

If you don't mind buying an extra bluetooth dongle, I definitely recommend using the PSNavi over bluetooth instead of USB.

**Comment by zelmon64** [comment]
@HipsterSloth I tested it and it still crashes. The only time it didn't crash was when I had do driver installed for the PSNavi (and so it wasn't detected by PSMS). I completely uninstalled ScpToolkit but it made no difference.

**Comment by TenchiMasaki** [comment]
Doesn't seem to crash anymore and test navi works, but got the following log not sure if it matters:

[2017-06-27 07:03:05.903]: main - Starting PSMoveService v0.9-alpha 8.6.0
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\USBManagerConfig.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\USBManagerConfig.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\NetworkManagerConfig.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\NetworkManagerConfig.json"
[2017-06-27 07:03:05.927]: USBAsyncRequestManager::startup - Requested LibUSBApi
[2017-06-27 07:03:05.929]: USBAsyncRequestManager::startup - Creating LibUSBApi
[2017-06-27 07:03:05.933]: USBAsyncRequestManager::startup - Initialized USB API
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\DeviceManagerConfig.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\DeviceManagerConfig.json"
[2017-06-27 07:03:05.941]: DeviceManager::startup - Platform Hotplug API is ENABLED
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2017-06-27 07:03:05.981]: bluetooth_get_host_address - Found a bluetooth radio
[2017-06-27 07:03:05.983]: bluetooth_get_host_address - Retrieved radio info
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\HMDManagerConfig.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\HMDManagerConfig.json"
libusb: error [init_device] device '\\.\USB#VID_046D&PID_C22D&MI_01#8&1C936E1&0&0001' is no longer connected!
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
[2017-06-27 07:03:06.133]: PSNaviController::open - Opening PSNaviController(USB\VID_054C&PID_042F\b4_p1.2)
[2017-06-27 07:03:06.135]: USBAsyncRequestManager::openUSBDevice - Successfully opened device -1
[2017-06-27 07:03:06.137]: PSNaviController::open -   Successfully opened USB handle 0
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\psnavi_04_76_6e_8d_53_29.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\psnavi_04_76_6e_8d_53_29.json"
[2017-06-27 07:03:06.220]: DeviceTypeManager::update_connected_devices - Device device_id 0 (PSNavi) opened
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [init_device] device '\\.\USB#VID_046D&PID_C22D&MI_01#8&1C936E1&0&0001' is no longer connected!
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [init_device] device '\\.\USB#VID_046D&PID_C22D&MI_01#8&1C936E1&0&0001' is no longer connected!
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
[2017-06-27 07:03:15.97]: PSMoveController::open - Opening PSMoveController(\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#9&10b5aef1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
[2017-06-27 07:03:15.104]: PSMoveController::open -   with serial_number: 04766e082467
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\04_76_6e_08_24_67.json"
Config file name: "C:\Users\tench\AppData\Roaming\PSMoveService\04_76_6e_08_24_67.json"
[2017-06-27 07:03:15.475]: DeviceTypeManager::update_connected_devices - Device device_id 1 (PSMove) opened
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [init_device] device '\\.\USB#VID_046D&PID_C22D&MI_01#8&1C936E1&0&0001' is no longer connected!
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [init_device] device '\\.\USB#VID_046D&PID_C22D&MI_01#8&1C936E1&0&0001' is no longer connected!
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [init_device] device '\\.\USB#VID_046D&PID_C22D&MI_01#8&1C936E1&0&0001' is no longer connected!
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
[2017-06-27 07:07:07.727]: ClientConnection::start - Starting client connection id 0
[2017-06-27 07:07:07.729]: ClientConnection::send_connection_info - Sending connection id to client 0
[2017-06-27 07:07:07.905]: ServerRequestHandler - Start controller(1) stream (pos=1,phys=1,raw_sens=0,cal_sens=0,trkr=0,roi=0)

**Comment by TenchiMasaki** [comment]
I never was able to get ScpToolkit to work with my BT Adapters, so previous test was without it.

**Comment by zelmon64** [comment]
@HipsterSloth after reinstalling ScpToolkit and going back to Release #1.3.0 I can't get the PSNavi to be detected. I tried deleting the contents of `%appdata%\PSMoveService\` to start again but it had no effect (I didn't know `"gamepad_api_enabled": "true"` is now the default). I can still attach controllers to the virtual controllers. I can't think what would have changed.

[PSMoveService.log.txt](https://github.com/HipsterSloth/PSMoveSteamVRBridge/files/1108925/PSMoveService.log.txt)

**Comment by HipsterSloth** [comment]
@zelmon64  This should be fixed in the latest. I was able to test the psnavi controller using both direct usb connection (the non-scpdrvier way) and with the scp driver over bluetooth.

As part of the virtual controller work I had also move some config values from 
`ControllerManagerConfig.json` to `DeviceManagerConfig.json` to deal with some header file dependency cleanup. Unfortunately I didn't version the config files like I should have so it can leave some people in a weird state.

Bottom line, your `DeviceManagerConfig.json` should look like this:
```
{
    "version": "1",
    "controller_reconnect_interval": "1000",
    "controller_poll_interval": "2",
    "tracker_reconnect_interval": "10000",
    "tracker_poll_interval": "13",
    "hmd_reconnect_interval": "10000",
    "hmd_poll_interval": "2",
    "gamepad_api_enabled": "true",
    "platform_api_enabled": "true"
}
```

And your ControllerManagerConfig.json should look like this:
```
{
    "version": "1",
    "virtual_controller_count": "0"
}
```

I'm going to mark this as resolved, but if you are still having problems please feel free to re-open.

**Comment by zelmon64** [comment]
@HipsterSloth it still crashes for me if the PSNavi is plugged in when I stop PSMS but if it works fine for you and TenchiMasaki it must be something on my end so I won't re-open this (I happy to just deal with it).

**Comment by HipsterSloth** [comment]
@zelmon64 Hmmm that's a bummer. If there is a crash I'd still like to get to the bottom of that. I'm wondering if the crash is in the USB manager when attempting to close the device? Do you happen to have have PSMS built locally? I'd love to see a callstack if possible. In the meantime I'll give a local repro a try.

Re-opening the issue and updating the name to reflect the current problem

**Comment by HipsterSloth** [comment]
@zelmon64 I think I see the problem. I'm shutting down the USB Manager before closing all of the devices. A psnavi controller connected via usb still needs to access the usb manager to close the usb connection. I'll make a hot fix for that now and post it here for you to test.

**Comment by HipsterSloth** [comment]
@zelmon64 Would you mind giving this build a try?

[PSMoveService_0.9_alpha8.6.3.zip](https://github.com/HipsterSloth/PSMoveSteamVRBridge/files/1121032/PSMoveService_0.9_alpha8.6.3.zip)

I usually shut down PSMoveService by closing the window which I think kills the process rather than doing a proper shutdown with Ctrl+C. Which is why I probably didn't catch this when doing the USB navi test.

**Comment by zelmon64** [comment]
@HipsterSloth that fixed it thanks! 

Doesn't closing the window leave the cameras on (or rather leave the red LED on)? I tried once to see if we could properly shutdown PSMoveService by closing the window but I couldn't come up with anything.

I'll re-close this now that it's definitely fixed =] .

**Comment by HipsterSloth** [comment]
@zelmon64 

> Doesn't closing the window leave the cameras on (or rather leave the red LED on)?

It sure does! I just sort of grew numb to it doing that. I think the device itself gets closed so the camera isn't "on", but the command to turn the red "led" off is never sent.

> I tried once to see if we could properly shutdown PSMoveService by closing the window but I couldn't come up with anything.

I honestly hadn't given installing a window close hook any though until you had mentioned it. I just did a quick search and it looks like you can install a console close hook using SetControlCtrlHandler:

https://msdn.microsoft.com/en-us/library/ms686016(VS.85).aspx

I might add that next release. Because I fell into the habit of just closing the window I frequently miss shutdown bugs like this one. This has also bit @cboulay in the past when he's done tests on OS X. He'll use Ctrl+C on the console on OS X and then uncover a shutdown crash that's actually been there a while, but I never noticed because I wasn't exercising that code path.
